#include "Renderer.h"
#include <algorithm>
#include <array>
#include <string>
#include <vector>
namespace {
struct V{glm::vec2 p;glm::vec4 c;glm::vec2 uv;float textured;};
void rect(std::vector<V>&v,float x,float y,float w,float h,glm::vec4 c,int W,int H){float l=x/W*2-1,r=(x+w)/W*2-1,t=1-y/H*2,b=1-(y+h)/H*2;v.insert(v.end(),{{{l,t},c,{0,0},0},{{l,b},c,{0,0},0},{{r,b},c,{0,0},0},{{l,t},c,{0,0},0},{{r,b},c,{0,0},0},{{r,t},c,{0,0},0}});}
int spriteIndex(Item item){switch(item){case Item::Grass:return 0;case Item::Dirt:return 1;case Item::Stone:return 2;case Item::Sand:return 3;case Item::Log:return 4;case Item::Leaves:return 5;case Item::Water:return 6;case Item::CoalOre:return 7;case Item::IronOre:return 8;case Item::GoldOre:return 9;case Item::CopperOre:return 10;case Item::DiamondOre:return 11;case Item::Planks:return 12;case Item::Stick:return 13;case Item::CraftingTable:return 14;case Item::Torch:return 15;case Item::Seeds:return 16;case Item::Wheat:return 17;case Item::Bread:return 18;case Item::RawMeat:return 19;case Item::WoodPickaxe:return 20;case Item::StonePickaxe:return 21;case Item::IronPickaxe:return 22;case Item::WoodAxe:return 23;case Item::StoneAxe:return 24;case Item::IronAxe:return 25;case Item::WoodShovel:return 26;case Item::StoneShovel:return 27;case Item::IronShovel:return 28;default:return -1;}}
void sprite(std::vector<V>&v,Item item,float x,float y,float w,float h,int W,int H,float alpha=1){int n=spriteIndex(item);if(n<0)return;int col=n%6,row=n/6;float u0=col/6.f,v0=row/5.f,u1=(col+1)/6.f,v1=(row+1)/5.f;float l=x/W*2-1,r=(x+w)/W*2-1,t=1-y/H*2,b=1-(y+h)/H*2;glm::vec4 c(1,1,1,alpha);v.insert(v.end(),{{{l,t},c,{u0,v0},1},{{l,b},c,{u0,v1},1},{{r,b},c,{u1,v1},1},{{l,t},c,{u0,v0},1},{{r,b},c,{u1,v1},1},{{r,t},c,{u1,v0},1}});}
const std::array<unsigned char,7>& digit(char c){static const std::array<std::array<unsigned char,7>,12>d={{{14,17,19,21,25,17,14},{4,12,4,4,4,4,14},{14,17,1,2,4,8,31},{30,1,1,14,1,1,30},{2,6,10,18,31,2,2},{31,16,16,30,1,1,30},{14,16,16,30,17,17,14},{31,1,2,4,8,8,8},{14,17,17,14,17,17,14},{14,17,17,15,1,1,14},{0,0,0,31,0,0,0},{0,0,0,0,0,0,0}}};if(c>='0'&&c<='9')return d[c-'0'];if(c=='-')return d[10];return d[11];}
void number(std::vector<V>&v,const std::string&s,float x,float y,float scale,glm::vec4 c,int W,int H){for(char ch:s){auto&r=digit(ch);for(int yy=0;yy<7;++yy)for(int xx=0;xx<5;++xx)if(r[yy]&(1<<(4-xx)))rect(v,x+xx*scale,y+yy*scale,scale,scale,c,W,H);x+=6*scale;}}
void icon(std::vector<V>&v,const ItemStack&s,float x,float y,float size,int W,int H){if(s.empty())return;sprite(v,s.item,x+2,y+2,size-4,size-4,W,H);if(s.count>1){std::string n=std::to_string(s.count);number(v,n,x+size-4-static_cast<float>(n.size())*6,y+size-11,1,{1,1,1,1},W,H);}int max=Inventory::maxDurability(s.item);if(max>0){float f=std::clamp(static_cast<float>(s.durability)/max,0.f,1.f);rect(v,x+5,y+size-6,size-10,3,{.08f,.08f,.08f,1},W,H);rect(v,x+5,y+size-6,(size-10)*f,3,{1-f,f,.08f,1},W,H);}}
void slot(std::vector<V>&v,const ItemStack&s,float x,float y,float z,int W,int H,bool selected=false){if(selected)rect(v,x-3,y-3,z+6,z+6,{.96f,.96f,.96f,1},W,H);rect(v,x,y,z,z,{.08f,.08f,.10f,.96f},W,H);rect(v,x+3,y+3,z-6,z-6,{.30f,.30f,.33f,.96f},W,H);icon(v,s,x,y,z,W,H);}
void flush(std::vector<V>&vertices,GLuint vbo,GLuint vao,GLuint program,GLuint texture){glBindBuffer(GL_ARRAY_BUFFER,vbo);glBufferData(GL_ARRAY_BUFFER,static_cast<GLsizeiptr>(vertices.size()*sizeof(V)),vertices.data(),GL_STREAM_DRAW);glDisable(GL_DEPTH_TEST);glDisable(GL_CULL_FACE);glEnable(GL_BLEND);glBlendFunc(GL_SRC_ALPHA,GL_ONE_MINUS_SRC_ALPHA);glUseProgram(program);glActiveTexture(GL_TEXTURE0);glBindTexture(GL_TEXTURE_2D,texture);glUniform1i(glGetUniformLocation(program,"uItemAtlas"),0);glBindVertexArray(vao);glDrawArrays(GL_TRIANGLES,0,static_cast<GLsizei>(vertices.size()));glBindVertexArray(0);glDisable(GL_BLEND);glEnable(GL_CULL_FACE);glEnable(GL_DEPTH_TEST);}
}
void Renderer::renderSurvivalUi(int W,int H,const Inventory&inv,float hunger,float xp,int level,bool fullbright)const{std::vector<V>v;float s=44,g=4,total=9*s+8*g,start=(W-total)*.5f,y=static_cast<float>(H)-58.f;for(int i=0;i<9;++i){const auto&stack=inv.slot(i);int max=Inventory::maxDurability(stack.item);if(max>0){float f=std::clamp(static_cast<float>(stack.durability)/max,0.f,1.f);rect(v,start+i*(s+g)+5,y+s-6,(s-10)*f,3,{1-f,f,.05f,1},W,H);}}for(int i=0;i<10;++i){float filled=std::clamp(hunger-i*2.f,0.f,2.f)/2.f;float x=start+total-14-i*18,hy=y-20;rect(v,x,hy,14,11,{.13f,.08f,.02f,.9f},W,H);if(filled>0)rect(v,x+2,hy+2,10*filled,7,{.92f,.60f,.12f,1},W,H);}rect(v,start,y-9,total,5,{.03f,.04f,.03f,.9f},W,H);rect(v,start+2,y-7,(total-4)*std::clamp(xp,0.f,1.f),2,{.28f,.95f,.18f,1},W,H);number(v,std::to_string(level),W*.5f-5,y-23,1.5f,{.45f,1,.28f,1},W,H);if(fullbright){rect(v,static_cast<float>(W)-144.f,12.f,132.f,22.f,{.08f,.08f,.04f,.82f},W,H);number(v,"1",static_cast<float>(W)-26.f,16.f,1.5f,{1,.88f,.2f,1},W,H);}flush(v,uiVbo_,uiVao_,uiProgram_,itemTexture_);}
void Renderer::renderInventory(int W,int H,const Inventory&inv,bool table,double mx,double my)const{std::vector<V>v;float px=W*.5f-325,py=H*.5f-280,s=44,g=4,start=px+100;rect(v,0,0,W,H,{0,0,0,.35f},W,H);rect(v,px,py,650,560,{.08f,.075f,.07f,.97f},W,H);rect(v,px+10,py+10,630,540,{.34f,.34f,.34f,.98f},W,H);for(int y=0;y<3;++y)for(int x=0;x<9;++x)slot(v,inv.slot(9+y*9+x),start+x*(s+g),py+300+y*(s+g),s,W,H);for(int x=0;x<9;++x)slot(v,inv.slot(x),start+x*(s+g),py+470,s,W,H,x==inv.selectedSlot());int n=table?3:2;for(int y=0;y<n;++y)for(int x=0;x<n;++x)slot(v,inv.craftSlot(y*3+x),px+70+x*(s+g),py+80+y*(s+g),s,W,H);rect(v,px+278,py+140,34,6,{.72f,.72f,.72f,1},W,H);rect(v,px+302,py+132,10,22,{.72f,.72f,.72f,1},W,H);slot(v,inv.craftingOutput(table),px+330,py+125,s,W,H);number(v,table?"3":"2",px+70,py+48,2,{.95f,.9f,.74f,1},W,H);icon(v,inv.cursorStack(),static_cast<float>(mx)-22,static_cast<float>(my)-22,44,W,H);flush(v,uiVbo_,uiVao_,uiProgram_,itemTexture_);}
void Renderer::renderHeldItem(int W,int H,const ItemStack&stack,float swing)const{if(stack.empty())return;std::vector<V>v;float wave=std::sin(std::clamp(swing,0.f,1.f)*3.1415926f),size=168.f,x=W-size-28.f+wave*28.f,y=H-size+25.f+wave*34.f;sprite(v,stack.item,x,y,size,size,W,H,.98f);flush(v,uiVbo_,uiVao_,uiProgram_,itemTexture_);}
void Renderer::renderUnderwaterOverlay(int W,int H)const{std::vector<V>v;rect(v,0,0,static_cast<float>(W),static_cast<float>(H),{.02f,.20f,.36f,.28f},W,H);flush(v,uiVbo_,uiVao_,uiProgram_,itemTexture_);}
