#include "Survival.h"
#include "Player.h"
#include "World.h"
#include <algorithm>
#include <cmath>
#include <cstring>
#include <fstream>
#include <limits>
#include <random>
#include <sstream>

namespace {
constexpr char InventoryMagic[8]={'V','X','I','N','V','4','\0','\0'};
constexpr char MobMagic[8]={'V','X','M','O','B','1','\0','\0'};
bool pick(Item i){return i==Item::WoodPickaxe||i==Item::StonePickaxe||i==Item::IronPickaxe;}
bool axe(Item i){return i==Item::WoodAxe||i==Item::StoneAxe||i==Item::IronAxe;}
bool shovel(Item i){return i==Item::WoodShovel||i==Item::StoneShovel||i==Item::IronShovel;}
int tier(Item i){if(i==Item::IronPickaxe||i==Item::IronAxe||i==Item::IronShovel)return 3;if(i==Item::StonePickaxe||i==Item::StoneAxe||i==Item::StoneShovel)return 2;if(i==Item::WoodPickaxe||i==Item::WoodAxe||i==Item::WoodShovel)return 1;return 0;}
template<class T>bool wr(std::ofstream&f,const T&v){f.write(reinterpret_cast<const char*>(&v),sizeof(v));return!!f;}
template<class T>bool rd(std::ifstream&f,T&v){f.read(reinterpret_cast<char*>(&v),sizeof(v));return!!f;}
bool same(Item item,const ItemStack&s){return !s.empty()&&s.item==item;}
bool raySphere(const glm::vec3&o,const glm::vec3&direction,const glm::vec3&center,float reach,float radius,float&along){glm::vec3 d=glm::normalize(direction),delta=center-o;along=glm::dot(delta,d);return along>=0&&along<=reach&&glm::length(delta-d*along)<=radius;}

struct Recipe{int w,h;std::array<Item,9> cells{};Item output;int count;bool table;};
Recipe recipe(int w,int h,std::initializer_list<Item> cells,Item output,int count,bool table){Recipe r;r.w=w;r.h=h;r.output=output;r.count=count;r.table=table;std::copy(cells.begin(),cells.end(),r.cells.begin());return r;}
const std::vector<Recipe>& recipes(){static const std::vector<Recipe> all=[](){std::vector<Recipe>r;
 r.push_back(recipe(1,1,{Item::Log},Item::Planks,4,false));
 r.push_back(recipe(1,2,{Item::Planks,Item::Planks},Item::Stick,4,false));
 r.push_back(recipe(1,2,{Item::CoalOre,Item::Stick},Item::Torch,4,false));
 r.push_back(recipe(2,2,{Item::Planks,Item::Planks,Item::Planks,Item::Planks},Item::CraftingTable,1,false));
 r.push_back(recipe(3,1,{Item::Wheat,Item::Wheat,Item::Wheat},Item::Bread,1,true));
 for(Item m:{Item::Planks,Item::Stone,Item::IronOre}){Item p=m==Item::Planks?Item::WoodPickaxe:(m==Item::Stone?Item::StonePickaxe:Item::IronPickaxe);Item a=m==Item::Planks?Item::WoodAxe:(m==Item::Stone?Item::StoneAxe:Item::IronAxe);Item s=m==Item::Planks?Item::WoodShovel:(m==Item::Stone?Item::StoneShovel:Item::IronShovel);
  r.push_back(recipe(3,3,{m,m,m,Item::None,Item::Stick,Item::None,Item::None,Item::Stick,Item::None},p,1,true));
  r.push_back(recipe(2,3,{m,m,m,Item::Stick,Item::None,Item::Stick},a,1,true));
  r.push_back(recipe(1,3,{m,Item::Stick,Item::Stick},s,1,true));}
 return r;}();return all;}
}

Inventory::Inventory(){add(Item::Grass,12);add(Item::Log,4);add(Item::Torch,6);add(Item::WoodPickaxe,1);add(Item::Seeds,6);add(Item::Bread,2);}
void Inventory::selectSlot(int s){selectedSlot_=std::clamp(s,0,8);}void Inventory::cycleSlot(int d){selectedSlot_=(selectedSlot_+d)%9;if(selectedSlot_<0)selectedSlot_+=9;}
Item Inventory::selectedItem()const{return selectedStack().empty()?Item::None:selectedStack().item;}const ItemStack&Inventory::selectedStack()const{return slots_[selectedSlot_];}
const ItemStack&Inventory::slot(int i)const{static ItemStack none;return i>=0&&i<TotalSlots?slots_[i]:none;}const ItemStack&Inventory::craftSlot(int i)const{static ItemStack none;return i>=0&&i<CraftSlots?crafting_[i]:none;}
int Inventory::count(Item item)const{int n=0;for(const auto&s:slots_)if(s.item==item)n+=s.count;return n;}
int Inventory::maxStack(Item i){return isTool(i)?1:(i==Item::None?0:64);}int Inventory::maxDurability(Item i){return tier(i)==1?60:(tier(i)==2?132:(tier(i)==3?251:0));}
void Inventory::normalize(ItemStack&s){if(s.item==Item::None||s.count<=0){s.clear();return;}s.count=std::min(s.count,maxStack(s.item));int d=maxDurability(s.item);s.durability=d?std::clamp(s.durability,1,d):0;}
bool Inventory::canMerge(const ItemStack&a,const ItemStack&b){return !a.empty()&&!b.empty()&&a.item==b.item&&!isTool(a.item);}
int Inventory::add(Item item,int amount,int durability){if(item==Item::None||amount<=0)return amount;int max=maxStack(item);if(!isTool(item))for(auto&s:slots_)if(s.item==item&&s.count<max){int n=std::min(amount,max-s.count);s.count+=n;amount-=n;if(!amount)return 0;}for(auto&s:slots_)if(s.empty()){int n=std::min(amount,max);s={item,n,isTool(item)?(durability<0?maxDurability(item):durability):0};normalize(s);amount-=n;if(!amount)return 0;}return amount;}
bool Inventory::remove(Item item,int amount){if(count(item)<amount)return false;for(auto&s:slots_)if(s.item==item&&amount){int n=std::min(amount,s.count);s.count-=n;amount-=n;normalize(s);}return true;}
bool Inventory::consumeSelected(int n){auto&s=slots_[selectedSlot_];if(s.count<n)return false;s.count-=n;normalize(s);return true;}bool Inventory::damageSelectedTool(int n){auto&s=slots_[selectedSlot_];if(!isTool(s.item))return false;s.durability-=n;if(s.durability<=0)s.clear();return true;}
void Inventory::clickStack(ItemStack&slot,ItemStack&cursor,bool right){normalize(slot);normalize(cursor);if(!right){if(cursor.empty()){cursor=slot;slot.clear();}else if(slot.empty()){slot=cursor;cursor.clear();}else if(canMerge(slot,cursor)){int n=std::min(cursor.count,maxStack(slot.item)-slot.count);slot.count+=n;cursor.count-=n;normalize(cursor);}else std::swap(slot,cursor);}else{if(cursor.empty()&&!slot.empty()){int n=(slot.count+1)/2;cursor=slot;cursor.count=n;slot.count-=n;normalize(slot);}else if(!cursor.empty()&&slot.empty()){slot=cursor;slot.count=1;--cursor.count;normalize(cursor);}else if(canMerge(slot,cursor)&&slot.count<maxStack(slot.item)){++slot.count;--cursor.count;normalize(cursor);}}}

bool Inventory::findCraftingMatch(bool table,ItemStack&out,std::vector<int>*used)const{int grid=table?3:2;for(const Recipe&r:recipes()){if(r.table&&!table||r.w>grid||r.h>grid)continue;for(int oy=0;oy<=grid-r.h;++oy)for(int ox=0;ox<=grid-r.w;++ox)for(int mirror=0;mirror<(r.w>1?2:1);++mirror){bool ok=true;std::vector<int>indices;for(int y=0;y<grid;++y)for(int x=0;x<grid;++x){Item expected=Item::None;if(x>=ox&&x<ox+r.w&&y>=oy&&y<oy+r.h){int rx=x-ox;if(mirror)rx=r.w-1-rx;expected=r.cells[(y-oy)*r.w+rx];}int ci=y*3+x;Item actual=crafting_[ci].empty()?Item::None:crafting_[ci].item;if(actual!=expected){ok=false;break;}if(expected!=Item::None)indices.push_back(ci);}if(ok){out={r.output,r.count,maxDurability(r.output)};if(used)*used=indices;return true;}}}out.clear();return false;}
ItemStack Inventory::craftingOutput(bool table)const{ItemStack out;findCraftingMatch(table,out,nullptr);return out;}
bool Inventory::takeCraftingOutput(bool table){ItemStack out;std::vector<int>used;if(!findCraftingMatch(table,out,&used))return false;if(cursor_.empty())cursor_=out;else if(canMerge(cursor_,out)&&cursor_.count+out.count<=maxStack(out.item))cursor_.count+=out.count;else return false;for(int i:used){--crafting_[i].count;normalize(crafting_[i]);}return true;}
bool Inventory::handleInventoryClick(double mx,double my,int w,int h,bool right,bool table,bool shift){float px=w*.5f-325,py=h*.5f-280,s=44,g=4,start=px+100;auto inside=[&](float x,float y){return mx>=x&&mx<x+s&&my>=y&&my<y+s;};auto quick=[&](int source,int first,int last){ItemStack moving=slots_[source];if(moving.empty())return true;if(!isTool(moving.item))for(int i=first;i<last&&moving.count;++i)if(canMerge(slots_[i],moving)){int n=std::min(moving.count,maxStack(moving.item)-slots_[i].count);slots_[i].count+=n;moving.count-=n;}for(int i=first;i<last&&moving.count;++i)if(slots_[i].empty()){int n=std::min(moving.count,maxStack(moving.item));slots_[i]=moving;slots_[i].count=n;moving.count-=n;}slots_[source]=moving;normalize(slots_[source]);return true;};if(inside(px+330,py+125))return takeCraftingOutput(table);int n=table?3:2;for(int y=0;y<n;++y)for(int x=0;x<n;++x){int i=y*3+x;if(inside(px+70+x*(s+g),py+80+y*(s+g))){clickStack(crafting_[i],cursor_,right);return true;}}for(int y=0;y<3;++y)for(int x=0;x<9;++x)if(inside(start+x*(s+g),py+300+y*(s+g))){int i=9+y*9+x;if(shift)return quick(i,0,9);clickStack(slots_[i],cursor_,right);return true;}for(int x=0;x<9;++x)if(inside(start+x*(s+g),py+470)){if(shift)return quick(x,9,36);clickStack(slots_[x],cursor_,right);return true;}return false;}
ItemStack Inventory::takeCursor(bool one){ItemStack r;if(cursor_.empty())return r;if(one){r=cursor_;r.count=1;--cursor_.count;normalize(cursor_);}else{r=cursor_;cursor_.clear();}return r;}
void Inventory::returnCraftingItems(){for(auto&s:crafting_)if(!s.empty()){int left=add(s.item,s.count,s.durability);s.count=left;normalize(s);}}
bool Inventory::save(const std::string&p,std::uint32_t seed)const{std::ofstream f(p,std::ios::binary|std::ios::trunc);if(!f)return false;f.write(InventoryMagic,8);wr(f,seed);wr(f,selectedSlot_);auto ws=[&](const ItemStack&s){std::uint8_t i=static_cast<std::uint8_t>(s.item);std::int16_t c=static_cast<std::int16_t>(s.count),d=static_cast<std::int16_t>(s.durability);return wr(f,i)&&wr(f,c)&&wr(f,d);};for(const auto&s:slots_)if(!ws(s))return false;for(const auto&s:crafting_)if(!ws(s))return false;return ws(cursor_);}
bool Inventory::load(const std::string&p,std::uint32_t seed){std::ifstream f(p,std::ios::binary);if(!f)return false;char m[8]{};std::uint32_t stored=0;f.read(m,8);if(std::memcmp(m,InventoryMagic,8)||!rd(f,stored)||stored!=seed||!rd(f,selectedSlot_))return false;auto rs=[&](ItemStack&s){std::uint8_t i;std::int16_t c,d;if(!rd(f,i)||!rd(f,c)||!rd(f,d)||i>=static_cast<std::uint8_t>(Item::Count))return false;s={static_cast<Item>(i),c,d};normalize(s);return true;};for(auto&s:slots_)if(!rs(s))return false;for(auto&s:crafting_)if(!rs(s))return false;if(!rs(cursor_))return false;selectSlot(selectedSlot_);return true;}
bool Inventory::runCraftingSelfTest(std::string&report){Inventory i;for(auto&s:i.slots_)s.clear();auto test=[&](bool table,std::initializer_list<std::pair<int,Item>>set,Item expected){for(auto&s:i.crafting_)s.clear();i.cursor_.clear();for(auto [slot,item]:set)i.crafting_[slot]={item,1,0};ItemStack out=i.craftingOutput(table);if(out.item!=expected||!i.takeCraftingOutput(table))return false;for(auto [slot,item]:set)if(!i.crafting_[slot].empty())return false;return true;};bool ok=test(false,{{0,Item::Log}},Item::Planks)&&test(false,{{0,Item::Planks},{1,Item::Planks},{3,Item::Planks},{4,Item::Planks}},Item::CraftingTable)&&test(true,{{0,Item::Planks},{1,Item::Planks},{2,Item::Planks},{4,Item::Stick},{7,Item::Stick}},Item::WoodPickaxe)&&test(true,{{3,Item::Wheat},{4,Item::Wheat},{5,Item::Wheat}},Item::Bread);report=ok?"2x2 and 3x3 shaped recipes consumed correctly":"crafting recipe regression";return ok;}

Block itemToBlock(Item i){switch(i){case Item::Grass:return Block::Grass;case Item::Dirt:return Block::Dirt;case Item::Stone:return Block::Stone;case Item::Sand:return Block::Sand;case Item::Log:return Block::Log;case Item::Leaves:return Block::Leaves;case Item::Water:return Block::Water;case Item::CoalOre:return Block::CoalOre;case Item::IronOre:return Block::IronOre;case Item::GoldOre:return Block::GoldOre;case Item::CopperOre:return Block::CopperOre;case Item::DiamondOre:return Block::DiamondOre;case Item::Planks:return Block::Planks;case Item::CraftingTable:return Block::CraftingTable;case Item::Torch:return Block::Torch;default:return Block::Air;}}
Item blockToItem(Block b){switch(b){case Block::Grass:return Item::Grass;case Block::Dirt:return Item::Dirt;case Block::Stone:return Item::Stone;case Block::Sand:return Item::Sand;case Block::Log:return Item::Log;case Block::Leaves:return Item::Leaves;case Block::Water:return Item::Water;case Block::CoalOre:return Item::CoalOre;case Block::IronOre:return Item::IronOre;case Block::GoldOre:return Item::GoldOre;case Block::CopperOre:return Item::CopperOre;case Block::DiamondOre:return Item::DiamondOre;case Block::Planks:return Item::Planks;case Block::CraftingTable:return Item::CraftingTable;case Block::Torch:return Item::Torch;default:return Item::None;}}
bool isTool(Item i){return pick(i)||axe(i)||shovel(i);}bool isFood(Item i){return i==Item::Bread||i==Item::RawMeat||i==Item::RawBeef||i==Item::RawPork||i==Item::CookedBeef||i==Item::CookedPork;}
float foodValue(Item i){if(i==Item::Bread)return 5;if(i==Item::CookedBeef||i==Item::CookedPork)return 7;if(i==Item::RawMeat||i==Item::RawBeef||i==Item::RawPork)return 3;return 0;}
float attackDamage(Item i){int t=tier(i);if(axe(i))return 4.f+t*2.f;if(pick(i))return 2.5f+t*1.25f;if(shovel(i))return 2.f+t;return 1.f;}
float attackCooldown(Item i){return axe(i)?.85f:(pick(i)?.58f:(shovel(i)?.48f:.42f));}
float blockHardness(Block b){switch(b){case Block::Leaves:case Block::Torch:return .15f;case Block::Dirt:case Block::Grass:case Block::Sand:return .45f;case Block::Log:case Block::Planks:case Block::CraftingTable:return .9f;case Block::Stone:return 1.5f;case Block::CoalOre:case Block::CopperOre:return 2;case Block::IronOre:return 2.5f;case Block::GoldOre:return 3;case Block::DiamondOre:return 4;default:return .2f;}}
float toolBreakMultiplier(Item i,Block b){int t=tier(i);if(!t)return 1;float m=2+t*1.5f;if(pick(i)&&(b==Block::Stone||b==Block::CoalOre||b==Block::CopperOre||b==Block::IronOre||b==Block::GoldOre||b==Block::DiamondOre))return m;if(axe(i)&&(b==Block::Log||b==Block::Planks||b==Block::CraftingTable))return m;if(shovel(i)&&(b==Block::Dirt||b==Block::Grass||b==Block::Sand))return m;return 1;}
glm::vec3 itemColor(Item i){switch(i){case Item::Grass:return{.35f,.72f,.25f};case Item::Dirt:return{.48f,.31f,.16f};case Item::Stone:return{.5f};case Item::Sand:return{.86f,.78f,.48f};case Item::Log:return{.42f,.25f,.1f};case Item::Leaves:return{.2f,.62f,.18f};case Item::Water:return{.15f,.42f,.9f};case Item::CoalOre:return{.18f};case Item::IronOre:return{.72f,.57f,.45f};case Item::GoldOre:return{1,.75f,.12f};case Item::CopperOre:return{.76f,.38f,.2f};case Item::DiamondOre:return{.15f,.9f,.9f};case Item::Planks:return{.68f,.47f,.22f};case Item::Stick:return{.5f,.3f,.12f};case Item::CraftingTable:return{.62f,.39f,.18f};case Item::Torch:return{1,.68f,.1f};case Item::Seeds:return{.38f,.65f,.15f};case Item::Wheat:return{.92f,.74f,.18f};case Item::Bread:return{.82f,.52f,.16f};case Item::RawMeat:case Item::RawBeef:return{.8f,.16f,.18f};case Item::RawPork:return{.95f,.48f,.52f};case Item::Wool:return{.92f};case Item::CookedBeef:return{.42f,.18f,.10f};case Item::CookedPork:return{.72f,.38f,.25f};default:return isTool(i)?glm::vec3(.72f):glm::vec3(.7f);}}

SurvivalWorld::SurvivalWorld(std::uint32_t seed):seed_(seed){}std::int64_t SurvivalWorld::chunkKey(int x,int z){return(static_cast<std::int64_t>(x)<<32)^static_cast<std::uint32_t>(z);}
void SurvivalWorld::spawnDrop(const glm::vec3&p,Item item,int amount,int durability){if(item==Item::None||amount<=0)return;Drop d;d.position=p;d.velocity={.4f,.8f,.2f};d.stack={item,amount,isTool(item)?(durability<0?Inventory::maxDurability(item):durability):0};drops_.push_back(d);}
void SurvivalWorld::spawnExperience(const glm::vec3&p,int amount){int n=std::max(1,amount/2);for(int i=0;i<n;++i)experienceOrbs_.push_back({p+glm::vec3((i%3-.8f)*.12f,.2f,(i%2-.5f)*.15f),{0,.7f,0},std::max(1,amount/n),0});}
void SurvivalWorld::spawnNearbyAnimals(World&w,const glm::vec3&p){int cx=static_cast<int>(std::floor(p.x/CHUNK_SIZE)),cz=static_cast<int>(std::floor(p.z/CHUNK_SIZE));for(int dz=-2;dz<=2;++dz)for(int dx=-2;dx<=2;++dx){int x=cx+dx,z=cz+dz;auto key=chunkKey(x,z);if(!spawnedChunks_.insert(key).second)continue;std::mt19937 rng(seed_^static_cast<unsigned>(x*92837111)^static_cast<unsigned>(z*689287499));std::uniform_int_distribution<int>pos(1,CHUNK_SIZE-2),chance(0,99);if(chance(rng)>38)continue;int wx=x*CHUNK_SIZE+pos(rng),wz=z*CHUNK_SIZE+pos(rng),y=w.terrainHeight(wx,wz);Block ground=w.getBlock(wx,y,wz);if(ground!=Block::Grass&&ground!=Block::Sand)continue;Animal a;a.position={wx+.5f,y+1.01f,wz+.5f};a.type=ground==Block::Sand?AnimalType::Pig:static_cast<AnimalType>(chance(rng)%4);a.health=a.type==AnimalType::Wolf?12:(a.type==AnimalType::Cow?10:8);a.thinkTimer=.2f*(chance(rng)%10);animals_.push_back(a);}}
int SurvivalWorld::targetedAnimal(const glm::vec3&o,const glm::vec3&d,float reach)const{int best=-1;float bestT=std::numeric_limits<float>::max();for(int i=0;i<static_cast<int>(animals_.size());++i){const auto&a=animals_[i];if(a.deathTimer>0)continue;float t;if(raySphere(o,d,a.position+glm::vec3(0,.55f,0),reach,a.age<0?.38f:.68f,t)&&t<bestT){best=i;bestT=t;}}return best;}
MobTarget SurvivalWorld::raycastMob(const glm::vec3&o,const glm::vec3&d,float reach,const World&w,float blockDistance)const{MobTarget result;int i=targetedAnimal(o,d,std::min(reach,blockDistance));if(i<0)return result;float along=0;glm::vec3 center=animals_[i].position+glm::vec3(0,.55f,0);raySphere(o,d,center,reach,.7f,along);RayHit obstruction;if(w.raycast(o,d,along,obstruction)&&obstruction.distance+0.05f<along)return result;result={i,along,center};return result;}
AttackResult SurvivalWorld::attackMob(int index,Item held,bool critical,const glm::vec3&attacker){AttackResult r;if(index<0||index>=static_cast<int>(animals_.size()))return r;Animal&a=animals_[index];if(a.deathTimer>0||a.hurtCooldown>0)return r;r.hit=true;r.critical=critical;r.damage=attackDamage(held)*(critical?1.5f:1.f);r.position=a.position+glm::vec3(0,.55f,0);a.health-=r.damage;a.hurtCooldown=.34f;a.hurtFlash=.22f;glm::vec3 push=a.position-attacker;push.y=0;if(glm::dot(push,push)<.001f)push={1,0,0};else push=glm::normalize(push);a.velocity+=push*(critical?6.f:4.4f);a.velocity.y=critical?4.2f:3.f;if(a.health<=0){a.deathTimer=.65f;r.killed=true;releaseDrops(a);spawnExperience(a.position,4);}return r;}
void SurvivalWorld::releaseDrops(Animal&a){if(a.dropsReleased)return;a.dropsReleased=true;if(a.type==AnimalType::Cow)spawnDrop(a.position,Item::RawBeef,1+static_cast<int>(std::abs(a.position.x))%2);else if(a.type==AnimalType::Pig)spawnDrop(a.position,Item::RawPork,1+static_cast<int>(std::abs(a.position.z))%2);else if(a.type==AnimalType::Sheep)spawnDrop(a.position,Item::Wool,1);}
RenderCuboid SurvivalWorld::mobOutline(int i)const{if(i<0||i>=static_cast<int>(animals_.size()))return{};const Animal&a=animals_[i];float baby=a.age<0?.55f:1;return{a.position+glm::vec3(0,.53f*baby,0),glm::vec3(1.08f,.95f,.66f)*baby,{1,1,1}};}
bool SurvivalWorld::feedAnimal(const glm::vec3&o,const glm::vec3&d,Item food){int i=targetedAnimal(o,d,5);if(i<0)return false;Animal&a=animals_[i];bool ok=(a.type==AnimalType::Cow||a.type==AnimalType::Sheep)?food==Item::Wheat:(a.type==AnimalType::Pig?food==Item::Seeds:(food==Item::RawMeat||food==Item::RawBeef||food==Item::RawPork));if(!ok||a.breedingCooldown>0||a.age<0)return false;a.loveTimer=12;for(int j=0;j<static_cast<int>(animals_.size());++j)if(j!=i&&animals_[j].type==a.type&&animals_[j].loveTimer>0&&animals_[j].breedingCooldown<=0&&animals_[j].age>=0&&glm::distance(animals_[j].position,a.position)<5){Animal baby=a;baby.position=(a.position+animals_[j].position)*.5f;baby.age=-60;baby.loveTimer=0;baby.breedingCooldown=0;baby.health=a.type==AnimalType::Wolf?12:(a.type==AnimalType::Cow?10:8);animals_[j].loveTimer=0;animals_[j].breedingCooldown=45;a.loveTimer=0;a.breedingCooldown=45;animals_.push_back(baby);spawnExperience(baby.position,3);break;}return true;}
void SurvivalWorld::updateAnimal(Animal&a,float dt,World&w,Player&player,float daylight){a.attackCooldown=std::max(0.f,a.attackCooldown-dt);a.hurtCooldown=std::max(0.f,a.hurtCooldown-dt);a.hurtFlash=std::max(0.f,a.hurtFlash-dt);a.loveTimer=std::max(0.f,a.loveTimer-dt);a.breedingCooldown=std::max(0.f,a.breedingCooldown-dt);a.age=std::min(0.f,a.age+dt);if(a.deathTimer>0){a.deathTimer-=dt;a.position.y-=dt*.35f;return;}a.thinkTimer-=dt;glm::vec3 delta=player.position()-a.position;float dist=glm::length(delta);bool hostile=a.type==AnimalType::Wolf&&daylight<.25f;if(hostile&&dist<13){glm::vec2 flat(delta.x,delta.z);if(glm::dot(flat,flat)>.01f)a.heading=glm::normalize(flat);if(dist<1.35f&&a.attackCooldown<=0){RayHit hit;glm::vec3 from=a.position+glm::vec3(0,.65f,0),to=player.position()+glm::vec3(0,.9f,0),ray=to-from;float length=glm::length(ray);bool blocked=w.raycast(from,ray/length,length,hit)&&hit.distance<length-.1f;if(!blocked){player.damage(2);a.attackCooldown=1.25f;}}}else if(a.thinkTimer<=0){float angle=std::fmod(std::abs(std::sin(a.position.x*13.1f+a.position.z*7.3f+a.age))*31.4f,6.283f);a.heading={std::cos(angle),std::sin(angle)};a.thinkTimer=2+std::fmod(std::abs(a.position.x+a.position.z),3.f);}float speed=hostile?2.35f:.75f;glm::vec3 move(a.heading.x*speed+ a.velocity.x,0,a.heading.y*speed+a.velocity.z);glm::vec3 next=a.position+move*dt;int fy=static_cast<int>(std::floor(a.position.y+.05f));int ax=static_cast<int>(std::floor(next.x)),az=static_cast<int>(std::floor(next.z));if(w.isSolidAt(ax,fy,az)){if(!w.isSolidAt(ax,fy+1,az)&&!w.isSolidAt(ax,fy+2,az))next.y+=1;else{next.x=a.position.x;next.z=a.position.z;a.heading=-a.heading;}}a.velocity.x*=std::pow(.08f,dt);a.velocity.z*=std::pow(.08f,dt);a.velocity.y-=18*dt;next.y+=a.velocity.y*dt;int bx=static_cast<int>(std::floor(next.x)),bz=static_cast<int>(std::floor(next.z)),below=static_cast<int>(std::floor(next.y-.08f));if(w.isSolidAt(bx,below,bz)){next.y=below+1.01f;a.velocity.y=0;a.grounded=true;}else a.grounded=false;a.position=next;}
void SurvivalWorld::update(float dt,World&w,Player&p,Inventory&i,float day){spawnNearbyAnimals(w,p.position());for(auto&a:animals_)updateAnimal(a,dt,w,p,day);animals_.erase(std::remove_if(animals_.begin(),animals_.end(),[](const Animal&a){return a.deathTimer<0;}),animals_.end());for(auto&d:drops_){d.age+=dt;d.velocity.y-=9.8f*dt;glm::vec3 n=d.position+d.velocity*dt;if(w.isSolidAt(static_cast<int>(std::floor(n.x)),static_cast<int>(std::floor(n.y)),static_cast<int>(std::floor(n.z))))d.velocity={0};else d.position=n;if(glm::distance(d.position,p.position()+glm::vec3(0,.8f,0))<1.4f){int left=i.add(d.stack.item,d.stack.count,d.stack.durability);d.stack.count=left;}}drops_.erase(std::remove_if(drops_.begin(),drops_.end(),[](const Drop&d){return d.age>180||d.stack.count<=0;}),drops_.end());for(auto&o:experienceOrbs_){o.age+=dt;glm::vec3 target=p.position()+glm::vec3(0,.8f,0),delta=target-o.position;float dist=glm::length(delta);if(dist<7&&dist>.01f)o.velocity+=glm::normalize(delta)*(10.f*dt);o.velocity*=std::pow(.45f,dt);o.position+=o.velocity*dt;if(dist<.75f){p.addExperience(o.value);o.value=0;}}experienceOrbs_.erase(std::remove_if(experienceOrbs_.begin(),experienceOrbs_.end(),[](const ExperienceOrb&o){return o.age>120||o.value<=0;}),experienceOrbs_.end());if(animals_.size()>90)animals_.erase(animals_.begin(),animals_.begin()+(animals_.size()-90));}
std::vector<RenderCuboid> SurvivalWorld::renderCuboids()const{std::vector<RenderCuboid>out;out.reserve(animals_.size()*6+experienceOrbs_.size());for(const auto&a:animals_){float baby=a.age<0?.55f:1,death=a.deathTimer>0?std::max(.1f,a.deathTimer/.65f):1;glm::vec3 c=a.type==AnimalType::Cow?glm::vec3(.35f,.2f,.12f):(a.type==AnimalType::Pig?glm::vec3(.95f,.55f,.6f):(a.type==AnimalType::Sheep?glm::vec3(.9f):glm::vec3(.38f)));if(a.hurtFlash>0)c=glm::mix(c,glm::vec3(1,.04f,.03f),.8f);float scale=baby*death;out.push_back({a.position+glm::vec3(0,.55f*scale,0),glm::vec3(1,.85f,.55f)*scale,c});out.push_back({a.position+glm::vec3(a.heading.x*.42f,.75f*scale,a.heading.y*.42f),glm::vec3(.55f)*scale,c*1.08f});for(int j=0;j<4;++j)out.push_back({a.position+glm::vec3((j<2?-.3f:.3f)*scale,.18f,(j%2?-.22f:.22f)*scale),glm::vec3(.16f,.48f,.16f)*scale,c*.75f});}for(const auto&o:experienceOrbs_)out.push_back({o.position,glm::vec3(.14f),{.35f,1,.08f}});return out;}
std::vector<RenderItemSprite> SurvivalWorld::renderItemSprites()const{std::vector<RenderItemSprite>out;out.reserve(drops_.size());for(const auto&d:drops_)out.push_back({d.position,d.stack.item,.42f});return out;}
bool SurvivalWorld::save(const std::string&p,std::uint32_t seed)const{std::ofstream f(p,std::ios::binary|std::ios::trunc);if(!f)return false;f.write(MobMagic,8);wr(f,seed);std::uint32_t n=static_cast<std::uint32_t>(std::count_if(animals_.begin(),animals_.end(),[](const Animal&a){return a.deathTimer<=0;}));wr(f,n);for(const auto&a:animals_)if(a.deathTimer<=0){std::uint8_t type=static_cast<std::uint8_t>(a.type);wr(f,type);wr(f,a.position);wr(f,a.health);wr(f,a.age);}return!!f;}
bool SurvivalWorld::load(const std::string&p,std::uint32_t seed){std::ifstream f(p,std::ios::binary);if(!f)return false;char m[8]{};std::uint32_t stored=0,n=0;f.read(m,8);if(std::memcmp(m,MobMagic,8)||!rd(f,stored)||stored!=seed||!rd(f,n)||n>500)return false;std::vector<Animal>loaded;for(std::uint32_t k=0;k<n;++k){std::uint8_t type;Animal a;if(!rd(f,type)||type>3||!rd(f,a.position)||!rd(f,a.health)||!rd(f,a.age))return false;a.type=static_cast<AnimalType>(type);a.health=std::clamp(a.health,.1f,20.f);loaded.push_back(a);spawnedChunks_.insert(chunkKey(static_cast<int>(std::floor(a.position.x/CHUNK_SIZE)),static_cast<int>(std::floor(a.position.z/CHUNK_SIZE))));}animals_=std::move(loaded);return true;}
bool SurvivalWorld::runCombatSelfTest(World&w,Player&p,Inventory&i,std::string&report){auto oldAnimals=animals_,oldDrops=drops_;animals_.clear();drops_.clear();bool ok=true;std::array<AnimalType,4>types{AnimalType::Cow,AnimalType::Pig,AnimalType::Sheep,AnimalType::Wolf};std::array<Item,4>expected{Item::RawBeef,Item::RawPork,Item::Wool,Item::None};glm::vec3 origin=p.cameraPosition(),dir=p.lookDirection();for(int k=0;k<4;++k){Animal a;a.type=types[k];a.position=origin+dir*3.f-glm::vec3(0,.55f,0);a.health=types[k]==AnimalType::Wolf?12:(types[k]==AnimalType::Cow?10:8);animals_.push_back(a);MobTarget target=raycastMob(origin,dir,5,w,5);ok&=target.valid();while(target.valid()&&animals_[target.index].deathTimer<=0){animals_[target.index].hurtCooldown=0;attackMob(target.index,Item::IronAxe,false,p.position());}if(expected[k]!=Item::None)ok&=std::any_of(drops_.begin(),drops_.end(),[&](const Drop&d){return d.stack.item==expected[k];});else ok&=drops_.empty()||std::none_of(drops_.begin(),drops_.end(),[](const Drop&d){return d.stack.item==Item::Wool;});animals_.clear();drops_.clear();}Animal blocked;blocked.position=origin+dir*3.f-glm::vec3(0,.55f,0);animals_.push_back(blocked);ok&=!raycastMob(origin,dir,5,w,1.5f).valid();animals_=std::move(oldAnimals);drops_=std::move(oldDrops);report=ok?"cow pig sheep wolf targeting damage deaths drops and occlusion passed":"combat regression";return ok;}
